### ISSUE TITLE
Error in the .gitmodules URL

### ISSUE THREAD

**Issue by NicolasSompairac** [grst/immune_deconvolution_benchmark#20]
Hello,

When trying to clone the repo, I come across an error:

_fatal: repository 'https://github.com/grst/immundeconv.git/' not found_

This might be due to an error in the URL as the correct one should be:

**https://github.com/grst/immunedeconv.git/**

**Comment by grst** [comment]
Hi @NicolasSompairac,

thanks for the catch! Fixed now. 
Let me know if you have any further issues running the pipeline.

**Comment by NicolasSompairac** [comment]
Hello @grst,

Sure thing. Thank you for your prompt correction!
