### ISSUE TITLE
conda install snakemake  not working

### ISSUE THREAD

**Issue by deo999** [grst/immune_deconvolution_benchmark#21]
conda install snakemake giving following error in linux(centos7 and ubuntu) both
Fetching package metadata ...........

PackageNotFoundError: Packages missing in current channels:
            
  - snakemake

We have searched for the packages in the following channels:
            
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch

**Comment by grst** [comment]
Use the conda-forge channel. 
`-c conda-forge`

Will update the documentation...

**Comment by asifzubair** [comment]
[This](https://snakemake.readthedocs.io/en/stable/getting_started/installation.html) says that is should be:
```
conda install -c bioconda -c conda-forge snakemake
```

**Comment by grst** [comment]
Indeed! Updated.
Thanks for the catch!
