### ISSUE TITLE
how to chnge no of cores, amount of memory 

### ISSUE THREAD

**Issue by naveen584** [grst/immune_deconvolution_benchmark#22]
how to chnge no of cores, amount of memory and to choose one method instead of all.

**Comment by grst** [comment]
Have a look at

https://github.com/grst/immune_deconvolution_benchmark/blob/f651ed315a133af9c2752c0bc83bc9d83780af05/notebooks/config.R#L3

And

https://github.com/grst/immune_deconvolution_benchmark/blob/f651ed315a133af9c2752c0bc83bc9d83780af05/notebooks/config.R#L13.

The amount of memory is fixed per core, so if you don't have enough, use less cores.
