### ISSUE TITLE
Is it possible to use other datasets in this package?

### ISSUE THREAD

**Issue by HelloYiHan** [grst/immune_deconvolution_benchmark#25]
Hi Gregor Sturm,

This package is helpful to me. However, I was wondering if I could use other datasets, such as other single-cell RNA-Seq datasets or other RNAseq + FACS datasets, to benchmark deconvolution tools? 
I mean loading other datasets into this package and complete subsequent pipeline.

Best
Yi Han

**Comment by grst** [comment]
Hi Yi Han, 

sorry for the late reply, I was traveling again. 

It's not plug & play, unfortunately. 

What you can do is have a look at the individual Rmarkdown notebooks here:
https://github.com/grst/immune_deconvolution_benchmark/tree/master/notebooks

* `15_mixing_study` contains the part that simulates from a scRNA-seq dataset
* `20_validation_study` performs benchmarking using expression + FACS data. 

You can execute them interactively in Rstudio and replace the datasets. 
It requires a bit of digging into the code, though. But if you have a look at the datasets shipped with the pipeline, it shouldn't be too hard to bring your additional datasets in the same format.
